/**
 * Phase 9 — Valuation Method Registry
 * Defines technical specifications, input requirements, prohibitions, and limitations for 16 valuation methods.
 */

import { ValuationMethodId } from './ValuationTypes';

export interface ValuationMethodSpec {
  methodId: ValuationMethodId;
  name: string;
  category: 'RELATIVE' | 'INTRINSIC' | 'ASSET_BASED';
  applicableBusinessModels: string[]; // empty means universally applicable
  prohibitedBusinessModels: string[];
  requiredInputs: string[];
  optionalInputs: string[];
  prohibitedInputs: string[];
  methodologyDescription: string;
  formula: string;
  outputUnit: 'MULTIPLE' | 'PERCENT' | 'INR_PER_SHARE';
  assumptionIntensity: 'LOW' | 'MEDIUM' | 'HIGH';
  limitations: string[];
}

export const VALUATION_METHOD_REGISTRY: Record<ValuationMethodId, ValuationMethodSpec> = {
  PE: {
    methodId: 'PE',
    name: 'Price to Earnings (P/E)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'CONSUMER_DISCRETIONARY', 'IT_SERVICES', 'PHARMACEUTICALS', 'BANKING', 'NBFC'],
    prohibitedBusinessModels: ['EARLY_STAGE_LOSS_MAKING'],
    requiredInputs: ['currentPrice', 'reportedEps'],
    optionalInputs: ['peerMedianPe', 'historicalMedianPe'],
    prohibitedInputs: ['negativeEps'],
    methodologyDescription: 'Calculates the ratio of market price per share to reported annual diluted EPS.',
    formula: 'Current Market Price / Reported EPS',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Non-meaningful if EPS <= 0', 'Distorted by one-off exceptional items'],
  },
  TTM_PE: {
    methodId: 'TTM_PE',
    name: 'Trailing Twelve Months P/E (TTM P/E)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'CONSUMER_DISCRETIONARY', 'IT_SERVICES', 'PHARMACEUTICALS', 'BANKING', 'NBFC'],
    prohibitedBusinessModels: ['EARLY_STAGE_LOSS_MAKING'],
    requiredInputs: ['currentPrice', 'ttmEps'],
    optionalInputs: ['peerMedianPe'],
    prohibitedInputs: ['negativeTtmEps'],
    methodologyDescription: 'Calculates the ratio of current market price to trailing 12-month earnings per share.',
    formula: 'Current Market Price / TTM EPS',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Requires rolling quarterly data', 'Not assessable if TTM EPS is negative'],
  },
  FORWARD_PE: {
    methodId: 'FORWARD_PE',
    name: 'Forward P/E',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'CONSUMER_DISCRETIONARY', 'IT_SERVICES', 'PHARMACEUTICALS', 'BANKING', 'NBFC'],
    prohibitedBusinessModels: [],
    requiredInputs: ['currentPrice', 'forwardVerifiedEpsEstimate'],
    optionalInputs: ['consensusEps'],
    prohibitedInputs: ['unverifiedAnalystEstimate'],
    methodologyDescription: 'Calculates ratio of market price to verified next-year forward earnings estimate.',
    formula: 'Current Market Price / Forward Estimated EPS',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'HIGH',
    limitations: ['Requires verified forward estimate; returns NOT_ASSESSABLE if unverified'],
  },
  PB: {
    methodId: 'PB',
    name: 'Price to Book (P/B)',
    category: 'RELATIVE',
    applicableBusinessModels: ['BANKING', 'NBFC', 'HOUSING_FINANCE', 'INSURANCE', 'OPERATING_INDUSTRIAL', 'UTILITIES'],
    prohibitedBusinessModels: [],
    requiredInputs: ['currentPrice', 'bookValuePerShare'],
    optionalInputs: ['adjustedNavPerShare'],
    prohibitedInputs: ['negativeBookValue'],
    methodologyDescription: 'Calculates ratio of market price to net book equity per share.',
    formula: 'Current Market Price / Book Value Per Share',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Non-meaningful if net worth is negative', 'Understates value for asset-light IP businesses'],
  },
  EV_EBITDA: {
    methodId: 'EV_EBITDA',
    name: 'Enterprise Value to EBITDA (EV/EBITDA)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'COMMODITY_CYCLICAL', 'INFRASTRUCTURE', 'UTILITIES', 'TELECOM', 'HEALTHCARE'],
    prohibitedBusinessModels: ['BANKING', 'NBFC', 'HOUSING_FINANCE', 'INSURANCE', 'ASSET_MANAGEMENT'],
    requiredInputs: ['enterpriseValue', 'ebitda'],
    optionalInputs: ['peerMedianEvEbitda'],
    prohibitedInputs: ['negativeEbitda'],
    methodologyDescription: 'Calculates total firm value relative to cash operating earnings before D&A, interest, and taxes.',
    formula: 'Enterprise Value / EBITDA',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Prohibited for financial institutions', 'Non-meaningful if EBITDA <= 0'],
  },
  EV_SALES: {
    methodId: 'EV_SALES',
    name: 'Enterprise Value to Sales (EV/Sales)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'RETAIL', 'PLATFORM_AGGREGATOR', 'EARLY_STAGE_HIGH_GROWTH'],
    prohibitedBusinessModels: ['BANKING', 'NBFC', 'INSURANCE'],
    requiredInputs: ['enterpriseValue', 'revenue'],
    optionalInputs: ['peerMedianEvSales'],
    prohibitedInputs: ['zeroRevenue'],
    methodologyDescription: 'Calculates total firm value relative to top-line annual revenues.',
    formula: 'Enterprise Value / Revenue',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Ignores margin differences across peers'],
  },
  PRICE_TO_SALES: {
    methodId: 'PRICE_TO_SALES',
    name: 'Price to Sales (P/S)',
    category: 'RELATIVE',
    applicableBusinessModels: ['PLATFORM_AGGREGATOR', 'CONSUMER_DISCRETIONARY', 'IT_SERVICES'],
    prohibitedBusinessModels: ['BANKING', 'NBFC'],
    requiredInputs: ['marketCapitalization', 'revenue'],
    optionalInputs: ['peerMedianPs'],
    prohibitedInputs: [],
    methodologyDescription: 'Calculates market equity value relative to annual revenues.',
    formula: 'Market Capitalization / Revenue',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'LOW',
    limitations: ['Ignores capital structure and debt load'],
  },
  FCF_YIELD: {
    methodId: 'FCF_YIELD',
    name: 'Free Cash Flow Yield (FCF Yield)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'IT_SERVICES', 'CONSUMER_STAPLES', 'PHARMACEUTICALS'],
    prohibitedBusinessModels: ['BANKING', 'NBFC', 'INSURANCE'],
    requiredInputs: ['freeCashFlow', 'marketCapitalization'],
    optionalInputs: ['historicalFcfYield'],
    prohibitedInputs: [],
    methodologyDescription: 'Calculates the percentage yield of free cash flow to firm equity investors.',
    formula: '(Free Cash Flow / Market Capitalization) * 100',
    outputUnit: 'PERCENT',
    assumptionIntensity: 'LOW',
    limitations: ['Negative FCF yields must be explicitly flagged as operational cash burn'],
  },
  DIVIDEND_YIELD: {
    methodId: 'DIVIDEND_YIELD',
    name: 'Dividend Yield',
    category: 'RELATIVE',
    applicableBusinessModels: ['UTILITIES', 'REIT_REAL_ESTATE', 'INFRASTRUCTURE_TRUST_INVIT', 'MATURE_CASH_COW', 'BANKING'],
    prohibitedBusinessModels: [],
    requiredInputs: ['dividendPerShare', 'currentPrice'],
    optionalInputs: ['specialDividendAmount'],
    prohibitedInputs: ['annualizingOneOffSpecialDividends'],
    methodologyDescription: 'Calculates annual dividend distribution as a percentage of market price.',
    formula: '(Annual Ordinary DPS / Current Market Price) * 100',
    outputUnit: 'PERCENT',
    assumptionIntensity: 'LOW',
    limitations: ['Special non-recurring dividends must not be annualized without disclosure'],
  },
  PEG: {
    methodId: 'PEG',
    name: 'Price/Earnings to Growth (PEG)',
    category: 'RELATIVE',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'IT_SERVICES', 'PHARMACEUTICALS', 'CONSUMER_DISCRETIONARY'],
    prohibitedBusinessModels: ['BANKING', 'COMMODITY_CYCLICAL'],
    requiredInputs: ['pe', 'earningsGrowthRate'],
    optionalInputs: [],
    prohibitedInputs: ['negativeEarningsGrowth', 'negativePe'],
    methodologyDescription: 'Normalizes P/E multiple against positive multi-year earnings CAGR.',
    formula: 'P/E / (Earnings Growth Rate * 100)',
    outputUnit: 'MULTIPLE',
    assumptionIntensity: 'MEDIUM',
    limitations: ['Requires positive earnings growth and meaningful P/E'],
  },
  FCFF_DCF: {
    methodId: 'FCFF_DCF',
    name: 'Free Cash Flow to Firm DCF (FCFF DCF)',
    category: 'INTRINSIC',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'IT_SERVICES', 'CONSUMER_STAPLES', 'PHARMACEUTICALS', 'HEALTHCARE', 'INFRASTRUCTURE'],
    prohibitedBusinessModels: ['BANKING', 'NBFC', 'INSURANCE'],
    requiredInputs: ['revenue', 'revenueCagr', 'ebitMargin', 'taxRate', 'capex', 'changeInWorkingCapital', 'wacc', 'terminalGrowth'],
    optionalInputs: ['depreciationAndAmortization'],
    prohibitedInputs: ['waccLessThanTerminalGrowth'],
    methodologyDescription: '5-year explicit FCFF projection discounted at WACC plus Gordon Growth terminal value.',
    formula: 'Sum(FCFF_t / (1+WACC)^t) + PV(Terminal Value) - Net Debt',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'HIGH',
    limitations: ['Highly sensitive to WACC and terminal growth rate assumptions; WACC > g required'],
  },
  FCFE_DCF: {
    methodId: 'FCFE_DCF',
    name: 'Free Cash Flow to Equity DCF (FCFE DCF)',
    category: 'INTRINSIC',
    applicableBusinessModels: ['OPERATING_INDUSTRIAL', 'IT_SERVICES', 'CONSUMER'],
    prohibitedBusinessModels: ['BANKING', 'INSURANCE'],
    requiredInputs: ['netIncome', 'capex', 'changeInWorkingCapital', 'netBorrowing', 'costOfEquity', 'terminalGrowth'],
    optionalInputs: [],
    prohibitedInputs: [],
    methodologyDescription: 'Discounts equity cash flows after net debt issuance at Cost of Equity.',
    formula: 'Sum(FCFE_t / (1+Ke)^t) + PV(Terminal Equity Value)',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'HIGH',
    limitations: ['Sensitive to future leverage assumptions'],
  },
  DIVIDEND_DISCOUNT_MODEL: {
    methodId: 'DIVIDEND_DISCOUNT_MODEL',
    name: 'Dividend Discount Model (DDM)',
    category: 'INTRINSIC',
    applicableBusinessModels: ['BANKING', 'UTILITIES', 'REIT_REAL_ESTATE', 'MATURE_DIVIDEND_PAYER'],
    prohibitedBusinessModels: ['EARLY_STAGE_GROWTH', 'ZERO_DIVIDEND_GROWTH_COMPANIES'],
    requiredInputs: ['dividendPerShare', 'costOfEquity', 'dividendGrowthRate', 'terminalGrowthRate'],
    optionalInputs: [],
    prohibitedInputs: ['keLessThanTerminalGrowth'],
    methodologyDescription: 'Discounts projected dividend payouts at Cost of Equity for mature yield assets.',
    formula: 'Sum(DPS_t / (1+Ke)^t) + PV(Terminal Dividend Value)',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'MEDIUM',
    limitations: ['Requires regular dividend payment history'],
  },
  GORDON_GROWTH: {
    methodId: 'GORDON_GROWTH',
    name: 'Gordon Growth Model',
    category: 'INTRINSIC',
    applicableBusinessModels: ['UTILITIES', 'REIT_REAL_ESTATE'],
    prohibitedBusinessModels: ['HIGH_GROWTH_COMPANIES'],
    requiredInputs: ['dividendPerShare', 'costOfEquity', 'perpetualGrowthRate'],
    optionalInputs: [],
    prohibitedInputs: ['keLessThanPerpetualGrowth'],
    methodologyDescription: 'Single-stage constant perpetual growth model: DPS_1 / (Ke - g).',
    formula: 'DPS * (1 + g) / (Ke - g)',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'MEDIUM',
    limitations: ['Ke must strictly exceed g'],
  },
  NAV: {
    methodId: 'NAV',
    name: 'Net Asset Value (NAV)',
    category: 'ASSET_BASED',
    applicableBusinessModels: ['REIT_REAL_ESTATE', 'INFRASTRUCTURE_TRUST_INVIT', 'HOLDING_COMPANY', 'REAL_ESTATE_DEVELOPER'],
    prohibitedBusinessModels: ['IT_SERVICES', 'PLATFORM_AGGREGATOR'],
    requiredInputs: ['grossAssetValue', 'totalLiabilities', 'totalDebt', 'cash', 'sharesOutstanding'],
    optionalInputs: ['holdingCompanyDiscountPercent'],
    prohibitedInputs: [],
    methodologyDescription: 'Appraises net market value of underlying physical assets and investments less liabilities.',
    formula: '(Gross Asset Value - Total Debt - Liabilities + Cash) * (1 - Holding Discount) / Shares',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'MEDIUM',
    limitations: ['Requires verified physical asset appraisals; book value is not NAV'],
  },
  SOTP: {
    methodId: 'SOTP',
    name: 'Sum-Of-The-Parts (SOTP)',
    category: 'ASSET_BASED',
    applicableBusinessModels: ['CONGLOMERATE', 'DIVERSIFIED_HOLDING', 'MULTI_SEGMENT_OPERATING'],
    prohibitedBusinessModels: ['SINGLE_PRODUCT_COMPANY'],
    requiredInputs: ['segmentFinancials', 'segmentMultiples', 'netDebt', 'corporateOverhead'],
    optionalInputs: ['conglomerateDiscountPercent'],
    prohibitedInputs: ['missingSegmentBreakdowns'],
    methodologyDescription: 'Values each distinct business segment using its peer multiple and sums net of corporate overhead.',
    formula: 'Sum(Segment_i Value) - Net Debt - Corporate Overhead - Holding Discount',
    outputUnit: 'INR_PER_SHARE',
    assumptionIntensity: 'HIGH',
    limitations: ['Requires audited segment reporting'],
  },
};
