import { FormulaDefinition } from './CalculationTypes';

export const CALCULATION_VERSION = 'financial-metrics-v1';
export const METHODOLOGY_VERSION = 'india-equity-methodology-v1';

export class FormulaRegistry {
  private static formulas: Map<string, FormulaDefinition> = new Map([
    // =========================================================================
    // GROWTH FORMULAS
    // =========================================================================
    [
      'REVENUE_GROWTH',
      {
        formulaId: 'FORMULA_REVENUE_GROWTH_V1',
        formulaName: 'Revenue Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((Revenue_Current - Revenue_Previous) / Revenue_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['REVENUE'],
        applicableArchetypes: [
          'OPERATING_INDUSTRIAL',
          'LENDING_FINANCIAL',
          'NON_LENDING_FINANCIAL',
          'UTILITY_REGULATED',
          'CONGLOMERATE',
          'INFRASTRUCTURE_TRUST',
        ],
        applicabilityRules: 'Applicable across all business models with reported revenue / top-line operations.',
        denominatorRules: 'Previous period revenue must be positive. Zero previous revenue yields NOT_CALCULABLE. Negative base mapped to NEGATIVE_BASE or TURNAROUND.',
        missingInputPolicy: 'Returns MISSING_INPUT if either current or previous revenue fact is missing.',
        negativeInputPolicy: 'Maps to explicit growth status (NEGATIVE_BASE, TURNAROUND, DECLINE_FROM_LOSS).',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'EBITDA_GROWTH',
      {
        formulaId: 'FORMULA_EBITDA_GROWTH_V1',
        formulaName: 'EBITDA Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((EBITDA_Current - EBITDA_Previous) / EBITDA_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EBITDA'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Applicable to operating non-financial businesses. Not applicable for Lending / Banking financial institutions.',
        denominatorRules: 'Previous EBITDA must be positive. Zero base yields NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if either current or previous EBITDA is missing.',
        negativeInputPolicy: 'Negative base mapped to TURNAROUND (if current > 0) or DECLINE_FROM_LOSS (if current < previous).',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'EBIT_GROWTH',
      {
        formulaId: 'FORMULA_EBIT_GROWTH_V1',
        formulaName: 'EBIT Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((EBIT_Current - EBIT_Previous) / EBIT_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EBIT'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Operating earnings growth before interest and taxes for non-lending businesses.',
        denominatorRules: 'Previous EBIT must be positive. Zero base yields NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if either current or previous EBIT is missing.',
        negativeInputPolicy: 'Explicit status mapped on negative operating earnings base.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'PAT_GROWTH',
      {
        formulaId: 'FORMULA_PAT_GROWTH_V1',
        formulaName: 'PAT Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((PAT_Current - PAT_Previous) / PAT_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['PAT'],
        applicableArchetypes: [
          'OPERATING_INDUSTRIAL',
          'LENDING_FINANCIAL',
          'NON_LENDING_FINANCIAL',
          'UTILITY_REGULATED',
          'CONGLOMERATE',
          'INFRASTRUCTURE_TRUST',
        ],
        applicabilityRules: 'Net profit growth applicable across all corporate business models.',
        denominatorRules: 'Previous PAT must be non-zero. Zero base yields NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if either current or previous PAT fact is missing.',
        negativeInputPolicy: 'Loss in base year with profit in current year mapped to TURNAROUND.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'EPS_GROWTH',
      {
        formulaId: 'FORMULA_EPS_GROWTH_V1',
        formulaName: 'Diluted EPS Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((EPS_Current - EPS_Previous) / EPS_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EPS'],
        applicableArchetypes: [
          'OPERATING_INDUSTRIAL',
          'LENDING_FINANCIAL',
          'NON_LENDING_FINANCIAL',
          'UTILITY_REGULATED',
          'CONGLOMERATE',
          'INFRASTRUCTURE_TRUST',
        ],
        applicabilityRules: 'Per-share earnings trajectory accounting for share count changes.',
        denominatorRules: 'Previous EPS must be non-zero.',
        missingInputPolicy: 'Returns MISSING_INPUT if either current or previous EPS is missing.',
        negativeInputPolicy: 'Mapped to TURNAROUND if previous was negative and current is positive.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'CFO_GROWTH',
      {
        formulaId: 'FORMULA_CFO_GROWTH_V1',
        formulaName: 'CFO Growth (YoY)',
        category: 'GROWTH',
        formulaExpression: '((CFO_Current - CFO_Previous) / CFO_Previous) * 100',
        unit: 'PERCENT',
        requiredInputs: ['CFO'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Cash generated from operations growth for non-lending corporates.',
        denominatorRules: 'Previous CFO must be positive for standard percentage growth.',
        missingInputPolicy: 'Returns MISSING_INPUT if either CFO fact is missing.',
        negativeInputPolicy: 'Negative operating cash flow base mapped to explicit growth status.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],

    // =========================================================================
    // MARGIN FORMULAS
    // =========================================================================
    [
      'EBITDA_MARGIN',
      {
        formulaId: 'FORMULA_EBITDA_MARGIN_V1',
        formulaName: 'EBITDA Margin',
        category: 'MARGINS',
        formulaExpression: '(EBITDA / Revenue) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EBITDA', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Operating profitability before non-cash depreciation and capital structure costs.',
        denominatorRules: 'Revenue must be positive. Revenue = 0 returns NOT_CALCULABLE. Revenue < 0 returns INVALID_INPUT.',
        missingInputPolicy: 'Returns MISSING_INPUT if EBITDA or Revenue is unavailable.',
        negativeInputPolicy: 'Negative EBITDA produces a valid negative operating margin.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'EBIT_MARGIN',
      {
        formulaId: 'FORMULA_EBIT_MARGIN_V1',
        formulaName: 'EBIT Margin (Operating Margin)',
        category: 'MARGINS',
        formulaExpression: '(EBIT / Revenue) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EBIT', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Operating profit margin after real economic asset depreciation.',
        denominatorRules: 'Revenue must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if EBIT or Revenue is missing.',
        negativeInputPolicy: 'Negative EBIT yields a valid negative margin.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'PAT_MARGIN',
      {
        formulaId: 'FORMULA_PAT_MARGIN_V1',
        formulaName: 'Net Profit Margin (PAT Margin)',
        category: 'MARGINS',
        formulaExpression: '(PAT / Revenue) * 100',
        unit: 'PERCENT',
        requiredInputs: ['PAT', 'REVENUE'],
        applicableArchetypes: [
          'OPERATING_INDUSTRIAL',
          'LENDING_FINANCIAL',
          'NON_LENDING_FINANCIAL',
          'UTILITY_REGULATED',
          'CONGLOMERATE',
          'INFRASTRUCTURE_TRUST',
        ],
        applicabilityRules: 'Bottom-line net margin across all business models.',
        denominatorRules: 'Revenue / Total Income must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if PAT or Revenue is missing.',
        negativeInputPolicy: 'Net loss yields a negative profit margin.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'CFO_MARGIN',
      {
        formulaId: 'FORMULA_CFO_MARGIN_V1',
        formulaName: 'CFO Margin (Cash Conversion Margin)',
        category: 'MARGINS',
        formulaExpression: '(CFO / Revenue) * 100',
        unit: 'PERCENT',
        requiredInputs: ['CFO', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Measures cash conversion intensity per rupee of top-line revenue.',
        denominatorRules: 'Revenue must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if CFO or Revenue is missing.',
        negativeInputPolicy: 'Operating cash deficit yields a negative CFO margin.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'FCF_MARGIN',
      {
        formulaId: 'FORMULA_FCF_MARGIN_V1',
        formulaName: 'Free Cash Flow Margin',
        category: 'MARGINS',
        formulaExpression: '((CFO - Capex) / Revenue) * 100',
        unit: 'PERCENT',
        requiredInputs: ['CFO', 'CAPEX', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Free cash flow generated as a percentage of revenue after qualifying capex.',
        denominatorRules: 'Revenue must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if CFO, Capex, or Revenue is missing.',
        negativeInputPolicy: 'Capex exceeding CFO yields negative FCF margin.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],

    // =========================================================================
    // CASH FLOW QUALITY FORMULAS
    // =========================================================================
    [
      'CFO_TO_PAT_RATIO',
      {
        formulaId: 'FORMULA_CFO_TO_PAT_V1',
        formulaName: 'CFO to PAT Ratio (Earnings Quality)',
        category: 'CASH_FLOW_QUALITY',
        formulaExpression: 'CFO / PAT',
        unit: 'RATIO',
        requiredInputs: ['CFO', 'PAT'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Earnings cash realization ratio. Baseline benchmark > 1.0x for healthy industrial corporates.',
        denominatorRules: 'PAT must be strictly positive (PAT > 0). PAT = 0 returns NOT_CALCULABLE. PAT < 0 returns NOT_CALCULABLE with diagnostic status (CASH_GENERATION_DURING_ACCOUNTING_LOSS or CASH_BURN_DURING_ACCOUNTING_LOSS).',
        missingInputPolicy: 'Returns MISSING_INPUT if CFO or PAT is missing.',
        negativeInputPolicy: 'Negative PAT yields NOT_CALCULABLE and attaches a non-interpretive diagnostic status.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'FREE_CASH_FLOW',
      {
        formulaId: 'FORMULA_FREE_CASH_FLOW_V1',
        formulaName: 'Free Cash Flow (FCF)',
        category: 'CASH_FLOW_QUALITY',
        formulaExpression: 'CFO - Qualifying_Capex',
        unit: 'INR_CRORE',
        requiredInputs: ['CFO', 'CAPEX'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Qualifying Capex specifically includes PPE & Intangible capital expenditures from Cash Flow from Investing.',
        denominatorRules: 'Pure subtraction; no denominator.',
        missingInputPolicy: 'Returns MISSING_INPUT if either CFO or Capex is missing.',
        negativeInputPolicy: 'Negative FCF indicates cash burn / heavy reinvestment.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],

    // =========================================================================
    // RETURN FORMULAS
    // =========================================================================
    [
      'ROE',
      {
        formulaId: 'FORMULA_ROE_AVERAGE_EQUITY_V1',
        formulaName: 'Return on Equity (ROE - Average Equity)',
        category: 'RETURNS',
        formulaExpression: '(PAT / ((Opening_Equity + Closing_Equity) / 2)) * 100',
        unit: 'PERCENT',
        requiredInputs: ['PAT', 'NET_WORTH'],
        applicableArchetypes: [
          'OPERATING_INDUSTRIAL',
          'LENDING_FINANCIAL',
          'NON_LENDING_FINANCIAL',
          'UTILITY_REGULATED',
          'CONGLOMERATE',
          'INFRASTRUCTURE_TRUST',
        ],
        applicabilityRules: 'Primary methodology uses Average Equity. Fallback uses Closing Equity with warning.',
        denominatorRules: 'Average/Closing Net Worth must be positive. Negative equity yields NOT_CALCULABLE.',
        missingInputPolicy: 'If opening equity is missing, falls back to Closing Equity with explicit warning.',
        negativeInputPolicy: 'Negative equity yields NOT_CALCULABLE (loss on negative equity is mathematically inverted).',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'ROCE',
      {
        formulaId: 'FORMULA_ROCE_AVERAGE_CAPITAL_EMPLOYED_V1',
        formulaName: 'Return on Capital Employed (ROCE - Average CE)',
        category: 'RETURNS',
        formulaExpression: '(EBIT / ((Opening_CE + Closing_CE) / 2)) * 100',
        unit: 'PERCENT',
        requiredInputs: ['EBIT', 'TOTAL_DEBT', 'NET_WORTH', 'CASH'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Capital Employed is defined as Total Debt + Net Worth - Cash & Cash Equivalents.',
        denominatorRules: 'Average/Closing Capital Employed must be positive. Non-positive CE yields NOT_CALCULABLE.',
        missingInputPolicy: 'Falls back to Closing Capital Employed with warning if opening balance is unavailable.',
        negativeInputPolicy: 'Negative CE yields NOT_CALCULABLE.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],

    // =========================================================================
    // LEVERAGE FORMULAS
    // =========================================================================
    [
      'DEBT_TO_EQUITY',
      {
        formulaId: 'FORMULA_DEBT_TO_EQUITY_V1',
        formulaName: 'Debt to Equity Ratio (D/E)',
        category: 'LEVERAGE',
        formulaExpression: 'Total_Debt / Net_Worth',
        unit: 'RATIO',
        requiredInputs: ['TOTAL_DEBT', 'NET_WORTH'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Measures financial leverage for non-lending corporate balance sheets.',
        denominatorRules: 'Net Worth must be positive. Negative equity yields NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if Total Debt or Net Worth is missing.',
        negativeInputPolicy: 'Negative equity yields NOT_CALCULABLE with explicit warning.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'NET_DEBT_TO_EBITDA',
      {
        formulaId: 'FORMULA_NET_DEBT_TO_EBITDA_V1',
        formulaName: 'Net Debt to EBITDA (Deleveraging Capacity)',
        category: 'LEVERAGE',
        formulaExpression: '(Total_Debt - Cash) / EBITDA',
        unit: 'RATIO',
        requiredInputs: ['TOTAL_DEBT', 'CASH', 'EBITDA'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Years of EBITDA required to retire net debt. Gated for non-lending corporates.',
        denominatorRules: 'EBITDA must be positive. Zero or negative EBITDA yields NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if Debt, Cash, or EBITDA is unavailable.',
        negativeInputPolicy: 'Zero or negative EBITDA returns NOT_CALCULABLE with explanation.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'INTEREST_COVERAGE',
      {
        formulaId: 'FORMULA_INTEREST_COVERAGE_V1',
        formulaName: 'Interest Coverage Ratio',
        category: 'LEVERAGE',
        formulaExpression: 'EBIT / Finance_Cost',
        unit: 'RATIO',
        requiredInputs: ['EBIT', 'FINANCE_COST'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE', 'INFRASTRUCTURE_TRUST'],
        applicabilityRules: 'Debt servicing ability from operating earnings.',
        denominatorRules: 'Finance Cost (Interest) must be positive. Zero or missing finance cost returns NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if EBIT or Finance Cost is missing.',
        negativeInputPolicy: 'Negative EBIT yields a negative coverage ratio.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],

    // =========================================================================
    // WORKING CAPITAL FORMULAS
    // =========================================================================
    [
      'RECEIVABLE_DAYS',
      {
        formulaId: 'FORMULA_RECEIVABLE_DAYS_V1',
        formulaName: 'Debtor Days (Receivable Days)',
        category: 'WORKING_CAPITAL',
        formulaExpression: '(Average_Receivables / Revenue) * 365',
        unit: 'DAYS',
        requiredInputs: ['RECEIVABLES', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'UTILITY_REGULATED', 'CONGLOMERATE'],
        applicabilityRules: 'Average collection period for receivables. Not applicable for Lending / Banking institutions.',
        denominatorRules: 'Revenue must be positive. Zero revenue returns NOT_CALCULABLE.',
        missingInputPolicy: 'Returns MISSING_INPUT if Receivables or Revenue is missing.',
        negativeInputPolicy: 'Negative receivables are invalid and return INVALID_INPUT.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'INVENTORY_DAYS',
      {
        formulaId: 'FORMULA_INVENTORY_DAYS_V1',
        formulaName: 'Inventory Days (Days Sales of Inventory)',
        category: 'WORKING_CAPITAL',
        formulaExpression: '(Average_Inventory / COGS) * 365',
        unit: 'DAYS',
        requiredInputs: ['INVENTORY', 'COGS'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'CONGLOMERATE'],
        applicabilityRules: 'Strict COGS denominator rule: If COGS is missing, returns MISSING_INPUT (never silently substitutes Revenue).',
        denominatorRules: 'COGS must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if COGS is unavailable.',
        negativeInputPolicy: 'Negative inventory returns INVALID_INPUT.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'PAYABLE_DAYS',
      {
        formulaId: 'FORMULA_PAYABLE_DAYS_V1',
        formulaName: 'Creditor Days (Payable Days)',
        category: 'WORKING_CAPITAL',
        formulaExpression: '(Average_Payables / COGS) * 365',
        unit: 'DAYS',
        requiredInputs: ['PAYABLES', 'COGS'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'CONGLOMERATE'],
        applicabilityRules: 'Strict COGS denominator rule: If COGS is missing, returns MISSING_INPUT.',
        denominatorRules: 'COGS must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if COGS is missing.',
        negativeInputPolicy: 'Negative payables return INVALID_INPUT.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'WORKING_CAPITAL_DAYS',
      {
        formulaId: 'FORMULA_WORKING_CAPITAL_DAYS_V1',
        formulaName: 'Working Capital Days (Average WC)',
        category: 'WORKING_CAPITAL',
        formulaExpression: '((Average_Receivables + Average_Inventory - Average_Payables) / Revenue) * 365',
        unit: 'DAYS',
        requiredInputs: ['RECEIVABLES', 'INVENTORY', 'PAYABLES', 'REVENUE'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'CONGLOMERATE'],
        applicabilityRules: 'Average Operating Working Capital (Average Receivables + Average Inventory - Average Payables) divided by Revenue * 365. Falls back to closing working capital if opening balances are missing.',
        denominatorRules: 'Revenue must be positive.',
        missingInputPolicy: 'Returns MISSING_INPUT if any of Receivables, Inventory, Payables, or Revenue is missing.',
        negativeInputPolicy: 'Negative working capital days (negative working capital cycle) is a valid economic result.',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
    [
      'CASH_CONVERSION_CYCLE',
      {
        formulaId: 'FORMULA_CASH_CONVERSION_CYCLE_V1',
        formulaName: 'Cash Conversion Cycle (CCC)',
        category: 'WORKING_CAPITAL',
        formulaExpression: 'Receivable_Days + Inventory_Days - Payable_Days',
        unit: 'DAYS',
        requiredInputs: ['RECEIVABLE_DAYS', 'INVENTORY_DAYS', 'PAYABLE_DAYS'],
        applicableArchetypes: ['OPERATING_INDUSTRIAL', 'CONGLOMERATE'],
        applicabilityRules: 'Total net operating cycle in days.',
        denominatorRules: 'Sum of component days.',
        missingInputPolicy: 'Returns MISSING_INPUT if any underlying component day metric is MISSING_INPUT.',
        negativeInputPolicy: 'Negative CCC indicates a cash-generative working capital model (e.g. FMCG/Auto OEM).',
        methodologyVersion: METHODOLOGY_VERSION,
        calculationVersion: CALCULATION_VERSION,
      },
    ],
  ]);

  public static getFormula(metricCode: string): FormulaDefinition | undefined {
    return this.formulas.get(metricCode);
  }

  public static getAllFormulas(): FormulaDefinition[] {
    return Array.from(this.formulas.values());
  }
}
